### ISSUE TITLE
first running problem

### ISSUE THREAD

**Issue by ajinkya-open** [initialstate/pi-sensor-free-presence-detector#1]
![screenshot from 2016-09-02 21-11-42](https://cloud.githubusercontent.com/assets/17094316/18209567/f3a049e0-7151-11e6-9cbc-c9726768c274.png)
i tried to run it in simple ubuntu os.. haven't configured any hardware for wifi, just using the basic modem in my laptop.. but here problem i think is about indentation..

![Uploading Screenshot from 2016-09-02 21-14-19.png…]()

**Comment by RChloe** [comment]
Indentation was correct, seems like a tabs mixed with spaces issue that doesn't appear when run on the Pi. Converted the file to all spaces - should work now.
