### ISSUE TITLE
Big delay

### ISSUE THREAD

**Issue by yirden** [initialstate/pi-sensor-free-presence-detector#2]
Good day. I have done everything according your instructions. As I understand arp-scan works each 30 seconds and terminal sees that device is either online or offline but in my dashboard at initialstate.com those events occur with a big delay (arround hour or sometimes even two). Is there any way to speed this up?

**Comment by RChloe** [comment]
Do you still have **streamer.flush()** inside of your script? Sometimes the streamer will buffer events before sending them, so if there aren't many events being sent, you could see a delay. The flush ensures that any logged events are sent immediately.
