### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Dannyj1984** [initialstate/pi-sensor-free-presence-detector#3]
Hi I am totally new to raspberry pi and coding, I wanted to give this a go for at home,

I have followed the instructions up to putting in the code, but not sure where I put this in? I recognise some of the code as python instructions, I am guessing I don't put this on the command line?

Sorry if it's a simple answer

Danny

**Comment by jrbail01** [comment]
Danny,

We have a great tutorial on getting started with Raspberry Pi that might help. The tutorial is at https://github.com/initialstate/piot-101/wiki https://github.com/initialstate/piot-101/wiki. The chapters that will help you get started with your particular question start at https://github.com/initialstate/piot-101/wiki/Part-2.-Hello-World https://github.com/initialstate/piot-101/wiki/Part-2.-Hello-World. 

Jamie Bailey
