### ISSUE TITLE
tee: ./is_example.py: Permission denied

### ISSUE THREAD

**Issue by robmarkcole** [initialstate/pi-sensor-free-presence-detector#4]
At step 3 I get `tee: ./is_example.py: Permission denied` and no example script is written.

**Comment by esaracho** [comment]
This step is not necessary, well, actually the example script is not necessary

**Comment by RChloe** [comment]
Esaracho is correct, you do not need the example script to complete the project. You can copy-paste it for testing from our [support pages](http://support.initialstate.com/knowledgebase/articles/590085-how-to-stream-events-in-python) or completely skip this step all together. Just make sure you add your access key from Initial State into all of your streaming scripts.
